'use client'
import { useState } from "react";
import { type NextPage } from "next";
import Head from "next/head";
import clsx from 'clsx'
import { add, format, isEqual, startOfWeek } from 'date-fns'
import { ptBR as ptBRLocale } from 'date-fns/locale'
import { CreateAvailableTimeModal } from "@/components/modals/CreateAvailableTimeModal";

export default function Home<NextPage>() {
  const [selectedWeek, setSelectedWeek] = useState(startOfWeek(new Date('May 10, 2023 03:24:00')))
  const [hours, setHours] = useState([8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])
  const [days, setDays] = useState([
    add(selectedWeek, { days: 0 }),
    add(selectedWeek, { days: 1 }),
    add(selectedWeek, { days: 2 }),
    add(selectedWeek, { days: 3 }),
    add(selectedWeek, { days: 4 }),
    add(selectedWeek, { days: 5 }),
    add(selectedWeek, { days: 6 }),
  ])
  const [openCreateAvailableTimeModal, setOpenCreateAvailableTimeModal] = useState(false)

  const events = [
    {
      start: new Date("May 8, 2023 16:00:00"),
      end: new Date("May 8, 2023 18:00:00"),
      name: 'task tal'
    },
    {
      start: new Date("May 11, 2023 12:00:00"),
      end: new Date("May 11, 2023 18:00:00"),
      name: 'task tal'
    }
  ]

  const availableHours = [
    {
      start: new Date("May 8, 2023 13:00:00"),
      end: new Date("May 8, 2023 20:00:00"),
    },
    {
      start: new Date("May 9, 2023 9:00:00"),
      end: new Date("May 9, 2023 13:00:00"),
    },
    {
      start: new Date("May 10, 2023 10:00:00"),
      end: new Date("May 10, 2023 14:00:00"),
    },
    {
      start: new Date("May 10, 2023 17:00:00"),
      end: new Date("May 10, 2023 21:00:00"),
    },
    {
      start: new Date("May 11, 2023 11:00:00"),
      end: new Date("May 11, 2023 20:00:00"),
    },
    {
      start: new Date("May 12, 2023 08:00:00"),
      end: new Date("May 12, 2023 20:00:00"),
    },
  ]

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Dev Calendar</h1>
      <main className="min-h-screen flex flex-col items-center justify-center bg-slate-950 text-white">
        <div className="text-4xl">
          Semana
        </div>
        <div className="flex w-4/5 justify-evenly">
          {days.map((day, dayIndex) => {
            return (
              <div className="flex flex-col w-full justify-evenly text-center bg-slate-500">
                <div>{format(day, 'EEEE', { locale: ptBRLocale })}</div>
                {hours.map((hour) => {
                  let dragging
                  const now = add(selectedWeek, { days: dayIndex, hours: hour })
                  const [isAvailable] = availableHours.filter(hour => new Date(hour.start) <= new Date(now) && new Date(hour.end) > new Date(now))
                  const [event] = events.filter(event => new Date(event.start) <= new Date(now) && new Date(event.end) > new Date(now))

                  const availableStart = isAvailable && isEqual(isAvailable.start, new Date(now))
                  const availableEnd = isAvailable && isEqual(isAvailable.end, add(new Date(now), { hours: 1 }))

                  const isEventStart = event && isEqual(new Date(event?.start), new Date(now))
                  const isEventEnd = event && isEqual(new Date(event?.end), add(new Date(now), { hours: 1 }))

                  if (isAvailable) {
                    return (
                      <div
                        className={clsx(
                          "w-60 h-12 bg-slate-400 text-black text-center",
                          availableStart && 'rounded-t-lg',
                          availableEnd && 'rounded-b-lg'
                        )}
                      >
                        <div
                          className={clsx(
                            event && "text-left h-12 bg-sky-400 text-black w-11/12 ml-1 pl-1",
                            isEventStart && 'rounded-t-lg',
                            isEventEnd && 'rounded-b-lg'
                          )}
                        >
                          {!!isEventStart && event?.name}
                        </div>
                      </div>
                    )
                  }

                  return (
                    <div
                      className="h-12 bg-slate-500 text-black text-center border border-black border-opacity-20"
                      onClick={() => setOpenCreateAvailableTimeModal(true)}
                      draggable
                      onDragOver={() => console.log('draggingOver')}
                      style={{ background: dragging ? 'red' : 'blue'}}
                    >
                    </div>
                  )

                })}
              </div>
            )
          }
          )}
        </div>
      </main>
      <CreateAvailableTimeModal open={openCreateAvailableTimeModal} onOpenChange={setOpenCreateAvailableTimeModal} />
    </>
  );
};